### ISSUE TITLE
Ignore short & duplicated yanks

### ISSUE THREAD

**Issue by 97-109-107** [frizinak/goclip#1]
**Thanks for writing & sharing exactly what I wanted :)**

As in the tiltle, I was wondering if it would be feasible to keep the clipboard history a bit more hygenic by avoiding duplicates and storing yanks shorter than 3(?) characters.

**Comment by frizinak** [comment]
Good to know someone other than me is using it ;).

Duplicates should be ignored, they are moved to the top of the list though. If you have double checked, let me know and I'll look into it.

I'll implement a min-length flag when I find the time.

ps: just out of curiosity: what window-manager are you running and are you using goclip in combination with fzf?

**Comment by 97-109-107** [comment]
With i3wm, I launch the script via:
``termite -t "fuzzy-clip" -e "zsh -c 'goclip | fzf | goclip -d'"``
And have the following line to make the window always float:
``for_window [title="fuzzy-clip"] floating enable``

**Comment by frizinak** [comment]
Added the -l flag.

Let me know if you get duplicate entries.
